FROM node:8

LABEL Name=pdf-converter Version=0.0.1

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		pdftk \
		libreoffice-writer \
	&& rm -r /var/lib/apt/lists/*


WORKDIR /srv/pdf-converter
COPY package.json .
COPY package-lock.json .
COPY dist/server.js .

RUN npm install --only=production

EXPOSE 3000

CMD [ "node", "/srv/pdf-converter/server.js" ]
